name: Bun CI

on:
  push:
    paths:
      - '.github/workflows/build.yml'
      - 'src/**'
    pull_request:
      branches:
        - main
      paths:
        - '.github/workflows/build.yml'
        - 'src/**'
    workflow_dispatch:

jobs:
  build:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Install bun
        uses: oven-sh/setup-bun@v1
      
      - name: Install dependencies
        run: bun install --frozen-lockfile
      
      - name: Lint
        run: bun lint
      
      - name: Transpile
        run: bun transpile
