name: Bun CD

on:
  push:
    paths:
      - '.github/workflows/bun.yml'
      - 'src/**'
      - 'Dockerfile'
    pull_request:
      branches:
        - main
      paths:
        - '.github/workflows/bun.yml'
        - 'src/**'
        - 'Dockerfile'
    workflow_dispatch:

jobs:
  build:
    uses: bitomic/utilities/.github/workflows/docker-build.yml@50496947b2283a700933500c1ad21b3f67c55053
